
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
spec:
  steps:
    - name: run-tests
      image: python:3.8
      script: |
        #!/bin/sh
        pip install nose
        nosetests
